--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/alexis/wallpapers/mob.png"

-- Special
background="#19181b"
foreground="#c5c5c6"
cursor="#c5c5c6"

-- Colors
color0="#19181b"
color1="#413d71"
color2="#7e3983"
color3="#847688"
color4="#877dca"
color5="#cb858c"
color6="#dc83dc"
color7="#c5c5c6"
color8="#525154"
color9="#413d71"
color10="#7e3983"
color11="#847688"
color12="#877dca"
color13="#cb858c"
color14="#dc83dc"
color15="#c5c5c6"
