--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/alexis/Images/Top/elden-ring-dead-giant.jpg"

-- Special
background="#161818"
foreground="#c4c5c5"
cursor="#c4c5c5"

-- Colors
color0="#161818"
color1="#24383c"
color2="#2b4145"
color3="#40595b"
color4="#507074"
color5="#5c7370"
color6="#567679"
color7="#c4c5c5"
color8="#505151"
color9="#24383c"
color10="#2b4145"
color11="#40595b"
color12="#507074"
color13="#5c7370"
color14="#567679"
color15="#c4c5c5"
