--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/alexis/Images/Top/abstract-dark-waves.jpg"

-- Special
background="#17181a"
foreground="#c5c5c5"
cursor="#c5c5c5"

-- Colors
color0="#17181a"
color1="#2c4063"
color2="#553b48"
color3="#385b81"
color4="#516483"
color5="#3d79a0"
color6="#587f9f"
color7="#c5c5c5"
color8="#515153"
color9="#2c4063"
color10="#553b48"
color11="#385b81"
color12="#516483"
color13="#3d79a0"
color14="#587f9f"
color15="#c5c5c5"
