return {
  'mhartington/oceanic-next',
  'dracula/vim',
  'haishanh/night-owl.vim',
  'Shadorain/shadotheme',
  'bluz71/vim-moonfly-colors',
  'rafamadriz/neon',
  'marko-cerovac/material.nvim',
  'sainnhe/gruvbox-material',
  {'bluz71/vim-nightfly-colors', name = "nightfly"},
  'sainnhe/sonokai',
  {
    'romgrk/doom-one.vim',
    lazy = false,
    priority = 1000
  },
  'wadackel/vim-dogrun',
  'arcticicestudio/nord-vim',
  'jnurmine/Zenburn',
  'gosukiwi/vim-atom-dark',
  'NLKNguyen/papercolor-theme',
  'jacoborus/tender.vim',
  'rakr/vim-one',
  'drewtempelmeyer/palenight.vim',
  'folke/tokyonight.nvim',
  'whatyouhide/vim-gotham',
  'rebelot/kanagawa.nvim',
  'cocopon/iceberg.vim',
  'pineapplegiant/spaceduck',
  'sainnhe/everforest',
  'junegunn/seoul256.vim',
  'EdenEast/nightfox.nvim',
  'ayu-theme/ayu-vim',
  'savq/melange',
  { 'catppuccin/nvim', lazy = false, name = 'catppuccin' },
  'kvrohit/mellow.nvim',
  'ribru17/bamboo.nvim',
  'skullamortis/forest.nvim'
}
