return  {
  'tjdevries/colorbuddy.vim',
  config = function()
    local Color, colors, Group, groups, styles = require('colorbuddy').setup()

    Color.new('jasper', '#db504a')
    Color.new('ramUmber', '#955e42')
    Color.new('powderBlue', '#8da9c4')
    Color.new('oldGold', '#bab700')
    Color.new('asparagus', '#60935d')
    Color.new('chineseViolet', '#78586f')
    Color.new('night', '#000f08')
    Color.new('gunmetal', '#1c3738')
    Color.new('nyanza', '#e5ffde')
    Color.new('plum', '#88498f')
    Color.new('ashGray', '#a0b2a6')
    Color.new('moonstone', '#779fa1')
    Color.new('columbiaBlue', '#a5c4d4')

    -- SteamPunk
    Color.new('st_bg', '#000000')
    Color.new('st_drkbrown', '#261717')
    Color.new('st_brown', '#350e10')
    Color.new('st_drkred', '#732a24')
    Color.new('st_red', '#7d1011')
    Color.new('st_drkorange', '#a64826')
    Color.new('st_orange', '#bf3e0a')
    Color.new('st_yellow', '#d66c14')
    Color.new('st_beige', '#bf926b')
    Color.new('st_fg', '#f2c879')
    Color.new('st_blue', '#51768C')
    Color.new('st_white', '#f2e0c9')

    Color.new('leather', '#8b4513')
    Color.new('copper', '#b87333')
    Color.new('brass', '#cd9575')
    Color.new('gold', '#ffd700')
    Color.new('purple', '#7e2276')
    Color.new('red', '#c30d0d')
    Color.new('green', '#225a09')
    Color.new('blue', '#4f6b82')
    Color.new('black', '#28292d')
    Color.new('gray', '#9ea1aa')
    Color.new('paper', '#cea668')
    Color.new('radioactive', '#46f74f')
    Color.new('white', '#c7d5ce')

    -- Group.new('Normal', colors.st_fg, colors.st_bg)
    -- Group.new('HtmlTagName', colors.copper)
    -- Group.new('Identifier', colors.copper)
    -- Group.new('Function', colors.copper)
    -- Group.new('Type', colors.gold)
    -- Group.new('String', colors.white)
    -- Group.new('phpRegion', colors.purple:light())
    -- Group.new('phpregion', colors.brass:light())
  end
}
