--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/alexis/wallpapers/obito.jpg"

-- Special
background="#221a14"
foreground="#c7c5c4"
cursor="#c7c5c4"

-- Colors
color0="#221a14"
color1="#ac8567"
color2="#aa692d"
color3="#ad9f8f"
color4="#73aa46"
color5="#867ba8"
color6="#aa282c"
color7="#c7c5c4"
color8="#59534e"
color9="#ac8567"
color10="#aa692d"
color11="#ad9f8f"
color12="#73aa46"
color13="#867ba8"
color14="#aa282c"
color15="#c7c5c4"
