--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/alexis/Images/Top/chateau-ambulant.jpg"

-- Special
background="#171818"
foreground="#c5c5c5"
cursor="#c5c5c5"

-- Colors
color0="#171818"
color1="#7e8739"
color2="#758981"
color3="#41bae4"
color4="#9ed23e"
color5="#b1df48"
color6="#c7d581"
color7="#c5c5c5"
color8="#515151"
color9="#7e8739"
color10="#758981"
color11="#41bae4"
color12="#9ed23e"
color13="#b1df48"
color14="#c7d581"
color15="#c5c5c5"
