--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/alexis/wallpapers/rainy-day.jpg"

-- Special
background="#0a0609"
foreground="#f2e3c8"
cursor="#f2e3c8"

-- Colors
color0="#0a0609"
color1="#9C6855"
color2="#E89F60"
color3="#DAAF61"
color4="#816F91"
color5="#BAA2B6"
color6="#E0AF97"
color7="#f2e3c8"
color8="#a99e8c"
color9="#9C6855"
color10="#E89F60"
color11="#DAAF61"
color12="#816F91"
color13="#BAA2B6"
color14="#E0AF97"
color15="#f2e3c8"
